import { asc } from "drizzle-orm";
import { ArrowLeft, DoorOpen } from "lucide-react";
import Link from "next/link";
import { saveRoomAction, toggleRoomAction } from "@/app/actions";
import { getDb } from "@/db";
import { rooms } from "@/db/schema";
import { requireAdmin } from "@/lib/session";

export default async function RoomsAdminPage() {
  await requireAdmin();
  const rows = await getDb().select().from(rooms).orderBy(asc(rooms.name));
  return <main className="shell page"><Link href="/admin" className="button button-quiet"><ArrowLeft size={16} />Admin</Link><div style={{ margin: "1.5rem 0" }}><div className="eyebrow"><DoorOpen size={14} style={{ display: "inline", marginRight: 5 }} />Spaces</div><h1 className="display" style={{ fontSize: "3.6rem", margin: ".5rem 0" }}>Rooms</h1></div><section className="card" style={{ padding: "1.2rem", marginBottom: "1rem" }}><h2>Add a room</h2><form action={saveRoomAction} style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: ".75rem", alignItems: "end" }}><label className="label">Name<input className="field" name="name" required /></label><label className="label">Capacity<input className="field" name="capacity" type="number" min={1} required /></label><label className="label">Color<input className="field" name="color" type="color" defaultValue="#6750e8" required /></label><label className="label">Amenities<input className="field" name="amenities" placeholder="Display, Whiteboard" /></label><button className="button button-primary">Add room</button></form></section><div style={{ display: "grid", gap: ".8rem" }}>{rows.map((room) => <section className="card" key={room.id} style={{ padding: "1rem", borderLeft: `7px solid ${room.color}`, opacity: room.active ? 1 : .62 }}><form action={saveRoomAction} style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: ".65rem", alignItems: "end" }}><input type="hidden" name="id" value={room.id} /><label className="label">Name<input className="field" name="name" defaultValue={room.name} /></label><label className="label">Capacity<input className="field" name="capacity" type="number" defaultValue={room.capacity} /></label><label className="label">Color<input className="field" name="color" type="color" defaultValue={room.color} /></label><label className="label">Amenities<input className="field" name="amenities" defaultValue={room.amenities.join(", ")} /></label><button className="button button-secondary">Save</button></form><form action={toggleRoomAction} style={{ marginTop: ".6rem" }}><input name="id" type="hidden" value={room.id} /><input name="active" type="hidden" value={String(!room.active)} /><button className={`button ${room.active ? "button-danger" : "button-quiet"}`}>{room.active ? "Deactivate" : "Reactivate"}</button></form></section>)}</div></main>;
}
